spring:
  application:
    name: codingagent
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/codingagent
    username: postgres
    password: ivoyant
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql-models/chat-session-model.sql
        - classpath:sql-models/assistant-model.sql
        - classpath:sql-models/agent-tool-model.sql
        - classpath:sql-models/tool-embedding-model.sql
        - classpath:sql-models/agent-skill-model.sql
        - classpath:sql-models/chat-tool-event-model.sql
  ai:
    azure:
      openai:
        api-key: 6P1vmDOsmn4ZmAvat7DhqSBtNZYVMNa0j26yaSZJNlb8iYGtb2mSJQQJ99CEACHYHv6XJ3w3AAAAACOGgt1l
        endpoint: https://aif-eu2-ov-np-01.openai.azure.com
        chat:
          options:
            deployment-name: gpt-5.2-chat
        embedding:
          options:
            deployment-name: text-embedding-3-large
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
azure:
  storage:
    blob:
      connection-string: "DefaultEndpointsProtocol=https;AccountName=openfga;AccountKey=3qRPjRUAleZDRiDuHaZxCcrPFLAABAeLK/lSIuIDPTTo1CBgnzFIg+TvPvynr1sL5EtL7aIofTix+AStN2labg==;EndpointSuffix=core.windows.net"
      skills-container: agent-skills
